### ISSUE TITLE
Text when creating new S3 buckets can be misleading

### ISSUE THREAD

**Issue by simonkrenger** [oscp/cloud-selfservice-portal-frontend#1]
When creating new S3 buckets with the SSP, some people have mentioned that the text on the website can be misleading. Some people do not make the connection between "Bucket-Name" above and "dein Name". Also, some people were confused by "dein Name".

The following line should be changed to something more specific, including an example:
https://github.com/oscp/cloud-selfservice-portal-frontend/blob/d28dc2bd419552daa7e46fe5b7d6ec770a7f00c3/src/components/aws/NewS3Bucket.vue#L33

Suggestions:
* "Der Name des S3-Buckets wird mit deinen Angaben wie folgt zusammengestellt:
\<sbb\>-**BucketName**-\<prod/nonprod\>
Beispiel: *sbb-my-bucket-prod* oder *sbb-my-app-prod*"

**Comment by ReToCode** [comment]
Fixed in #v1.1.2.
